MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.add_ResNet50_conv4_body
  NUM_CLASSES: 6
  FASTER_RCNN: True
  MASK_ON: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  # 2x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 180000
  STEPS: [0,100000,140000]
RPN:
  SIZES: (32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: ResNet.add_ResNet_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign
MRCNN:
  ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v0upshare
  RESOLUTION: 14
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default: GaussianFill
TRAIN:
  WEIGHTS: ../model/pre_train_model/pre_jinnan2_mask_model.pkl
  DATASETS: ('jinnan2_train',)
  SCALES: (600,700,800,)
  MAX_SIZE: 1333
  SNAPSHOT_ITERS: 10000
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
TEST:
  DATASETS: ('jinnan2_val',)
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 1.0
  COMPETITION_MODE: False
  #RPN_NMS_THRESH: 0.7
  #BBOX_AUG:
    #ENABLED: True
    #H_FLIP: True
    #SCALE_H_FLIP: True
    ##SCALE_SIZE_DEP: True #can not apply
    #ASPECT_RATIO_H_FLIP: True
  MASK_AUG:
    ENABLED: True
    H_FLIP: True
    SCALE_H_FLIP: True
    ASPECT_RATIO_H_FLIP: True
  #BBOX_VOTE:
    #ENABLED: True
  FORCE_JSON_DATASET_EVAL: True
  SOFT_NMS:
    ENABLED: False
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: ../model/mask_model
