MODEL:
  TYPE: retinanet
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 6
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  MAX_ITER: 20000
  STEPS: [0,5000,10000]
FPN:
  FPN_ON: True
  MULTILEVEL_RPN: True
  RPN_MAX_LEVEL: 7
  RPN_MIN_LEVEL: 3
  COARSEST_STRIDE: 128
  EXTRA_CONV_LEVELS: True
RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 4
  #SHARE_CLS_BBOX_TOWER: True
  ASPECT_RATIOS: (1.0, 2.0, 3.0,0.5, 0.33)
  SCALES_PER_OCTAVE: 3
  ANCHOR_SCALE: 4
  LOSS_GAMMA: 2.0
  LOSS_ALPHA: 0.25
TRAIN:
  WEIGHTS: ../model/pre_train_model/pre_jinnan2_model.pkl
  DATASETS: ('jinnan2_train',)
  SCALES: (600,700,800,)
  USE_FLIPPED: True
  SNAPSHOT_ITERS: 5000
  MAX_SIZE: 1333
  RPN_STRADDLE_THRESH: -1  # default 0
TEST:
  DATASETS: ('jinnan2_val',)
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.55
  RPN_PRE_NMS_TOP_N: 10000  # Per FPN level
  RPN_POST_NMS_TOP_N: 2000
  BBOX_VOTE:
    ENABLED: True
  SOFT_NMS:
    ENABLED: False
    SIGMA: 0.5
  BBOX_AUG:
    ENABLED: True
    H_FLIP: True
    SCALE_H_FLIP: True
    SCALE_SIZE_DEP: True
OUTPUT_DIR: ../model/object_detection_model
